# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0d8862a988fa9b47336ceac016352b369d09e3c9a7b31f86a71ffef3fca6e82f226c4ed57f5b72ac24e4acc8667d0da99ea1edc89715b42831cb2ee277bfb9e

test:
  secret_key_base: 70ccc7205d53560d670c247fd6b3a084360aab9b25969525b18047578d22e32b72471f16e17db05d722bfc22deef984968a3b562f56c94024633ceb440d49589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
